### ISSUE TITLE
ERROR: window init failed: Error while creating the backend

### ISSUE THREAD

**Issue by beatgammit** [thiolliere/ruga#1]
GNOME on Arch Linux using the recommended build instructions (`cargo build --release; ./target/release/ruga`).

Let me know if I can give you any more information.

**Comment by thiolliere** [comment]
Thanks for the report. (happy to see arch users, I was once but now I am on debian stretch)

First we can try to run with less window option.
The configuration is loaded from config.toml in the root directory.
the standard window config is:
````toml
[window]
vsync = true
multisampling = 2
fullscreen = true
fullscreen_on_primary_monitor = true
fullscreen_monitor = 0 # if not fullscreen_on_primary_monitor
dimension = [640,480] # if not fullscreen
```

can you try with:
````toml
[window]
vsync = false
multisampling = 0
fullscreen = false
fullscreen_on_primary_monitor = true
fullscreen_monitor = 0 # if not fullscreen_on_primary_monitor
dimension = [640,480] # if not fullscreen
```

If the error is still raised then we can validate that glium work on your machine
`git clone https://github.com/tomaka/glium; cd glium; cargo run --example teapot`

If teapot failed please open an issue at glium.
